#!/bin/sh
if [ $(df -h | grep nvme1n1 | awk '{print $5}' | cut -d '%' -f1) -gt 75 ]
then
    cd /jenkinsmaster/jobs
    list= $(du -a */builds | sort -n -r | head -n 9 | awk '{print $2}')
    for i in $list
    do
      cd /jenkinsmaster/jobs/
      cd $i
      ls -tr | head -n -6 | xargs rm -r
    done
fi
